(Define (squarer a b)
	(define (process-new-value)
		(if (has-value? b)
					(if (< (get-value b) 0)
									(error "square less than 0 -- SQUARER" (get-value b))
									(set-value! a (sqrt b) me)
									(if (has-value? a)
												(if (< get-value a) 0)
															(error "square less than 0 -- SQUARER" (get-value b))
														(multiplier (get-value a) (get-value a) b))))
		(define (process-forget-value) 
					(forget-value! a1 me)
					(forget-value! a2 me)
					(forget-value! a3 me)
						(process-new-value)))

		(define (me request)
			(cond ((eq? request 'I-have-a-value)(process-new-value))
						((eq? request 'I-Lost-my-value)(process-forget-value))
						(else (error "UNKNOWN request adder" request))))
	(connect a)
	(connect b)
	
	me)