	#|
The sine of an angle (specified in radians) can be computed by making use of the
approximation sin x x if x is sufficiently small, and the trigonometric identity

sin x = 3 sin x/3 - 4 sin^3 x/3

to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered
``sufficiently small'' if its magnitude is not greater than 0.1 radians.) These ideas are incorporated in the
following procedures:
(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
(if (not (> (abs angle) 0.1))
angle
(p (sine (/ angle 3.0)))))
a. How many times is the procedure p applied when (sine 12.15) is evaluated?
b. What is the order of growth in space and number of steps (as a function of a) used by the process
generated by the sine procedure when (sine a) is evaluated?
|#


a) procedure p is applied 5 times
sin(12.50)
p(sin(4.166667))
	p(p(sin(1.388889)))
		p(p(p(sin(0.46296296))))
			p(p(p(p(sin(0154320)))))
				p(p(p(p(p(sin(0.0514403)))))                                    
					p(p(p(p(p((0.0514403)))))                                    
				p(p(p(p(.15377643)))                                    
			p(p(p(.44678377))                                    
		p(p(.9836084))
	p(-.855683)                                    
(-0.06094723)

b)  
 





